130587134 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
112220972 + 0 mapped (85.94% : N/A)
130587134 + 0 paired in sequencing
65293567 + 0 read1
65293567 + 0 read2
103543036 + 0 properly paired (79.29% : N/A)
109999006 + 0 with itself and mate mapped
2221966 + 0 singletons (1.70% : N/A)
1221082 + 0 with mate mapped to a different chr
781889 + 0 with mate mapped to a different chr (mapQ>=5)
