47645260 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
47645260 + 0 mapped (100.00% : N/A)
47645260 + 0 paired in sequencing
23822630 + 0 read1
23822630 + 0 read2
47645260 + 0 properly paired (100.00% : N/A)
47645260 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
