35617708 + 0 in total (QC-passed reads + QC-failed reads)
35617708 + 0 primary
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
35617708 + 0 mapped (100.00% : N/A)
35617708 + 0 primary mapped (100.00% : N/A)
35617708 + 0 paired in sequencing
17808854 + 0 read1
17808854 + 0 read2
35617708 + 0 properly paired (100.00% : N/A)
35617708 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
