103324742 + 0 in total (QC-passed reads + QC-failed reads)
103324742 + 0 primary
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
88743784 + 0 mapped (85.89% : N/A)
88743784 + 0 primary mapped (85.89% : N/A)
103324742 + 0 paired in sequencing
51662371 + 0 read1
51662371 + 0 read2
81118596 + 0 properly paired (78.51% : N/A)
86127796 + 0 with itself and mate mapped
2615988 + 0 singletons (2.53% : N/A)
1633278 + 0 with mate mapped to a different chr
1004913 + 0 with mate mapped to a different chr (mapQ>=5)
