86503078 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
86503078 + 0 mapped (100.00% : N/A)
86503078 + 0 paired in sequencing
43251539 + 0 read1
43251539 + 0 read2
86503078 + 0 properly paired (100.00% : N/A)
86503078 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
