131071676 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
112785214 + 0 mapped (86.05% : N/A)
131071676 + 0 paired in sequencing
65535838 + 0 read1
65535838 + 0 read2
102952056 + 0 properly paired (78.55% : N/A)
109663234 + 0 with itself and mate mapped
3121980 + 0 singletons (2.38% : N/A)
1703478 + 0 with mate mapped to a different chr
1172096 + 0 with mate mapped to a different chr (mapQ>=5)
