44433864 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
44433864 + 0 mapped (100.00% : N/A)
44433864 + 0 paired in sequencing
22216932 + 0 read1
22216932 + 0 read2
44433864 + 0 properly paired (100.00% : N/A)
44433864 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
