111574640 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
95095426 + 0 mapped (85.23% : N/A)
111574640 + 0 paired in sequencing
55787320 + 0 read1
55787320 + 0 read2
86425514 + 0 properly paired (77.46% : N/A)
93125796 + 0 with itself and mate mapped
1969630 + 0 singletons (1.77% : N/A)
1035028 + 0 with mate mapped to a different chr
643170 + 0 with mate mapped to a different chr (mapQ>=5)
