114146802 + 0 in total (QC-passed reads + QC-failed reads)
114146802 + 0 primary
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
97434853 + 0 mapped (85.36% : N/A)
97434853 + 0 primary mapped (85.36% : N/A)
114146802 + 0 paired in sequencing
57073401 + 0 read1
57073401 + 0 read2
87967926 + 0 properly paired (77.07% : N/A)
94190528 + 0 with itself and mate mapped
3244325 + 0 singletons (2.84% : N/A)
1787522 + 0 with mate mapped to a different chr
1075841 + 0 with mate mapped to a different chr (mapQ>=5)
