66615704 + 0 in total (QC-passed reads + QC-failed reads)
66615704 + 0 primary
0 + 0 secondary
0 + 0 supplementary
22676244 + 0 duplicates
22676244 + 0 primary duplicates
66615704 + 0 mapped (100.00% : N/A)
66615704 + 0 primary mapped (100.00% : N/A)
66615704 + 0 paired in sequencing
33307852 + 0 read1
33307852 + 0 read2
66615704 + 0 properly paired (100.00% : N/A)
66615704 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
