104714846 + 0 in total (QC-passed reads + QC-failed reads)
104714846 + 0 primary
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
89828013 + 0 mapped (85.78% : N/A)
89828013 + 0 primary mapped (85.78% : N/A)
104714846 + 0 paired in sequencing
52357423 + 0 read1
52357423 + 0 read2
81575020 + 0 properly paired (77.90% : N/A)
86773912 + 0 with itself and mate mapped
3054101 + 0 singletons (2.92% : N/A)
1735686 + 0 with mate mapped to a different chr
1205488 + 0 with mate mapped to a different chr (mapQ>=5)
