---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Laura Cook

# Workflow and analysis of comparative craniofacial ChIP-seq work in the fat-tailed dunnart and mouse

This project involves a number of analysis for the generation of ChIP-seq data for the fat-tailed dunnart for comparison with the exisiting mouse data in ENCODE.

## Data

* [Dunnart experimental design and data generation](dunnart_experiment_overview.html)

* [Mouse data from ENCODE](mouse_data_ENCODE.html)

## Data preparation and peak calling

* [Dunnart data pre-processing](dunnart_data_processing.html)

    + Outlines read mapping, filtering, QC and peak calling.

* [Mouse read pre-processing](mouse_dunnart_data_processing_for_comparison.html)

    + Outlines aligned reads from ENCODE, QC and peak calling.
    + Also plots and tabulates QC for mouse and dunnart to compare

## Data analyses

* [Whole genome alignment between mouse and dunnart](whole_genome_alignment.html)

* [Dunnart peak characterisation](dunnart_peak_characterisation.html)

* Cross-species peak comparisons

  + [Mouse and dunnart peak features](mouse_dunnart_peak_features.html)
  
  + [Peak level](peak_level_comparisons.html)
  
  + [Gene level](gene_level_comparisons.html)
  
  + [Incorporating temporal mouse gene expression data](tcseq_expression_analysis.html)
